#!/usr/bin/env python3
"""生成 P1（M1–M5）与 P2（M6/M7/M9/M11 + L2 oracle、L3 链路）的黄金向量。

职责一句话
----------
把 `adi_model` 的**自身输出**转成定宽 hex 向量文件（`sim/vectors/p1_*.hex`、
`sim/vectors/p2_*.hex`），不做任何独立推导：M1 用 `mapper.dem_state_sequence`，
M2 用 `dem.split_switch_command` 的 `order` 取逆，M3 用 `split_switch_command` 的
`main_counts/sub_counts`，M5 用 `weight_calibration._terms` 的 `plus` 掩码；
P2 的 `adc2_dec` 用 `fixed_point.round_even_divide`，`recon_core` 的期望字一律来自
`FixedPointReconstructor.reconstruct`。闭式变换本身由 `sim/ref/dem_closed_form.py`
单独穷举验证，本脚本不重复那条逻辑。

唯一例外（**已在报告里声明**）：`div_floor` 的期望商用 Python 的 `a // d` —— 那是
`reconstruct` 自己写的同一个算子（`shifted // denominator`），不是第二份实现；
真正的独立判据在 TB 侧的定义式 `q*d <= a < (q+1)*d`。

物理模型与文献出处
------------------
不引入新模型。来源：`docs/rtl/P1_INTERFACE.md`、`docs/rtl/P2_INTERFACE.md`（接口与
向量格式，冻结）、`docs/rtl/RTL_ARITHMETIC_CONTRACT.md`（算术）、
`src/adi_model/{mapper,dem,weight_calibration,fixed_point,pipeline}.py`。

单位契约
--------
* 全部文件为定宽 hex，单空格分隔；`//` 开头为注释行，然后一行 `#DATA`，再是纯数字。
* 打包字段一律 **LSB = 地址 0**（与 P1 同一约定）。
* P2 的 signed 字段用二补码 hex（`_shex`）。

参数来源分级
------------
* 向量只承载模型已分级的值，不新增参数；`params.json` 已记录配置的完整分级。
* M4 的 dither 码**不在本脚本产出**：模型用 PCG64，RTL 无法复现，故 M4 走统计验收。

契约与不变量 / 适用域
--------------------
* **可复现**：同一 `Config` 下重复运行逐字节一致；`--check` 是漂移门禁。
* **适用域**：只覆盖 `paper_literal`（split，`dac_n_main=63/complete_range=True`）的拓扑；
  `H_ROT*W_ROT == 64`（即 `N_MAIN=63`）是 M2 闭式成立的前提。换拓扑须重新验证。
* 生成的向量会被**提交进仓库**，故文件体积受 pre-commit 的 512 KB 限制约束。
  `build_p2()` 对每个文件做硬性体积断言，超限直接失败而不是静默产出。

Usage::

    python tools/export_rtl_vectors.py --config paper_literal
    python tools/export_rtl_vectors.py --check
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from dataclasses import replace
from typing import Any

import numpy as np

from adi_model import Config
from adi_model.dem import split_switch_command
from adi_model.fixed_point import FixedPointReconstructor, round_even_divide
from adi_model.mapper import dem_state_sequence
from adi_model.timing import build_slice_plan
from adi_model.weight_calibration import CalibrationSpec, DigitalObservation, _terms

# 本导出器自己的激励波形选择（常数而非魔数，便于从外部复算）。
# 与 tools/export_rtl_params.py 的同名常量是各自独立的**选择**，不要求相等。
GOLDEN_TONE_NUM = 73
GOLDEN_TONE_DEN = 2048
GOLDEN_AMPLITUDE_FRAC = 0.8

M1_SAMPLES = 1024
M5_SIDS = (0, 1, 7, 8, 63, 64, 255, 511)
# 注意口径：code c 对应的主/子单位数是 (c // n_sub, c % n_sub)，不是 c 本身。
M5_MAIN_COUNTS = (0, 1, 2, 31, 32, 62, 63)
M5_SUB_COUNTS = (0, 1, 4, 7)


def _hex(value: int, digits: int) -> str:
    """Render a non-negative integer as fixed-width hex."""
    if value < 0:
        raise ValueError("_hex takes non-negative values; use _shex for signed fields")
    return f"{value:0{digits}x}"


def _shex(value: int, digits: int) -> str:
    """Render a signed integer as fixed-width two's-complement hex."""
    return f"{value & ((1 << (4 * digits)) - 1):0{digits}x}"


def _json_text(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False) + "\n"


def _write(path: pathlib.Path, text: str, *, check: bool, drift: list[str]) -> None:
    if check:
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            drift.append(str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


# ----------------------------------------------------------------------
# M1：DEM 状态推进（按 bank 内序号）
# ----------------------------------------------------------------------
def build_m1(cfg: Config) -> tuple[str, dict[str, Any]]:
    """Golden sid sequence for the model's real A/B bank alternation."""
    bank = np.arange(M1_SAMPLES, dtype=np.int64) % 2
    sid = dem_state_sequence(M1_SAMPLES, cfg, bank)
    lines = [
        "// p1_m1_sid.hex  (generated by tools/export_rtl_vectors.py)",
        f"// samples={M1_SAMPLES}  cols: n(4) bank(1) en_a(1) en_b(1) sid_exp(3)",
        "// DRIVE: en_a = (bank==0), en_b = (bank==1); sample sid_a/sid_b in that same cycle.",
        "#DATA",
    ]
    for n in range(M1_SAMPLES):
        en_a = 0 if bank[n] else 1
        en_b = 1 if bank[n] else 0
        lines.append(f"{_hex(n, 4)} {bank[n]} {en_a} {en_b} {_hex(int(sid[n]), 3)}")
    stats = {
        "samples": M1_SAMPLES,
        "distinct_sids": int(np.unique(sid).size),
        "first_sid_by_bank": {
            "0": int(sid[0]),
            "1": int(sid[1]),
        },
        "per_bank_all_states_seen": bool(
            np.unique(sid[bank == 0]).size == 512 and np.unique(sid[bank == 1]).size == 512
        ),
    }
    return "\n".join(lines) + "\n", stats


# ----------------------------------------------------------------------
# M2：物理地址 -> 逻辑位置（order 的逆）
# ----------------------------------------------------------------------
def build_m2(cfg: Config) -> tuple[str, dict[str, Any], dict[str, np.ndarray]]:
    """Exhaustive inverse-permutation golden for all 512 DEM states."""
    n_main, n_sub = int(cfg.dac_n_main), int(cfg.dac_n_sub)
    sids = np.arange(512, dtype=np.int64)
    command = split_switch_command(cfg, np.zeros(512), sids)

    main_logical = np.empty((512, n_main), dtype=np.int64)
    sub_logical = np.empty((512, n_sub), dtype=np.int64)
    for s in range(512):
        row = command.main_order[s]
        main_logical[s, row] = np.arange(n_main)  # j_inv[p] = position of p in main_order
        row_s = command.sub_order[s]
        sub_logical[s, row_s] = np.arange(n_sub)

    lines = [
        "// p1_m2_jinv.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: sid(3) main_logical[63](2 each) sub_logical[8](2 each)",
        "// main_logical[p] = logical position of physical main address p; MUST be a permutation of 0..62.",
        "#DATA",
    ]
    for s in range(512):
        fields = " ".join(_hex(int(v), 2) for v in main_logical[s])
        subfields = " ".join(_hex(int(v), 2) for v in sub_logical[s])
        lines.append(f"{_hex(s, 3)} {fields} {subfields}")

    ok_main = all(sorted(main_logical[s].tolist()) == list(range(n_main)) for s in range(512))
    ok_sub = all(sorted(sub_logical[s].tolist()) == list(range(n_sub)) for s in range(512))
    if not (ok_main and ok_sub):
        raise AssertionError("order is not a bijection: the DEM invariant would be broken")
    stats = {
        "states": 512,
        "main_addresses": n_main,
        "sub_addresses": n_sub,
        "cases": int(512 * (n_main + n_sub)),
        "bijection_verified": True,
    }
    return (
        "\n".join(lines) + "\n",
        stats,
        {"main_logical": main_logical, "sub_logical": sub_logical},
    )


# ----------------------------------------------------------------------
# M3：命令 -> 每 slice 主/子计数
# ----------------------------------------------------------------------
def _m3_counts(cfg_bridge: Config, codes: np.ndarray, sids: np.ndarray):
    command = split_switch_command(cfg_bridge, codes.astype(float), sids)
    return command.main_counts, command.sub_counts


def build_m3(cfg: Config) -> tuple[str, dict[str, Any]]:
    """Exhaustive (code, bridge, sid_low) golden plus directed clipping cases."""
    n_active = int(cfg.n_active)
    levels = int(cfg.dac_levels)
    plain = replace(cfg, dem_enable=True, dem_bridge_enable=False)
    bridged = replace(cfg, dem_enable=True, dem_bridge_enable=True)

    lines = [
        "// p1_m3.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: coarse(3) dither(2 signed) bridge(1) sid_low(1) "
        "main_count[8](2 each) sub_count[8](1 each) rdac_over(1)",
        "// exhaustive part: coarse 0..511 x dither=0 x bridge{0,1} x sid_low 0..7",
        "// directed part: coarse in {0,1,255,510,511} x dither in -8..8 (k formation + clipping)",
        "#DATA",
    ]

    exhaustive = 0
    for code in range(levels):
        for bridge in (0, 1):
            cfg_b = bridged if bridge else plain
            sid = np.full(1, 0, dtype=np.int64)
            for sid_low in range(n_active):
                sid[0] = sid_low
                mc, sc = _m3_counts(cfg_b, np.array([code]), sid)
                lines.append(
                    f"{_hex(code, 3)} {_shex(0, 2)} {bridge} {sid_low} "
                    + " ".join(_hex(int(v), 2) for v in mc[0])
                    + " "
                    + " ".join(_hex(int(v), 1) for v in sc[0])
                    + " 0"
                )
                exhaustive += 1

    directed = 0
    for code in (0, 1, 255, 510, 511):
        for dither in range(-8, 9):
            k = code + dither
            clipped = min(max(k, 0), levels - 1)
            over = int(k < 0 or k > levels - 1)
            mc, sc = _m3_counts(plain, np.array([clipped]), np.zeros(1, np.int64))
            lines.append(
                f"{_hex(code, 3)} {_shex(dither, 2)} 0 0 "
                + " ".join(_hex(int(v), 2) for v in mc[0])
                + " "
                + " ".join(_hex(int(v), 1) for v in sc[0])
                + f" {over}"
            )
            directed += 1

    stats = {"exhaustive_cases": exhaustive, "directed_cases": directed, "levels": levels}
    return "\n".join(lines) + "\n", stats


# ----------------------------------------------------------------------
# M5：温度计掩码
# ----------------------------------------------------------------------
def _m5_golden(cfg: Config, sids: np.ndarray, codes: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return the model's own (main_on, sub_on) masks of shape (N, n_active, n_units).

    ``_terms`` does not return the ON mask directly: it folds it into
    ``b_minus_dac = injection - v_fs*(2*plus - 1)`` and leaves ``signal`` at all
    ones. With the injection set to zero that affine map is exactly invertible, so
    the mask is recovered as ``(1 - b_minus_dac/v_fs) / 2``. The result is asserted
    binary, which is what makes this an extraction rather than a guess: if
    ``_terms`` ever changes that encoding, this raises instead of silently
    producing a wrong golden.

    只有 **sampling** 模式会在 `b_minus_dac` 上再叠加一层（掩码单位被改写成轨电压），
    其余模式（off / analog / quantizer）这个仿射关系都是精确可逆的 —— 早先这里写成
    "只允许 off"，过严，把 quantizer 的链路向量挡在了门外。
    """
    if cfg.dither_mode == "sampling":
        raise ValueError("M5 golden extraction is invalid for dither_mode='sampling'")
    spec = CalibrationSpec.from_config(cfg)
    n = len(sids)
    data = DigitalObservation(
        spec,
        np.tile(np.arange(spec.n_active, dtype=np.int64), (n, 1)),
        np.asarray(codes, dtype=float),
        np.asarray(sids, dtype=np.int64),
        np.zeros(n, dtype=np.int64),
        np.zeros(n),
        np.zeros(n),
        np.zeros(n, bool),
        True,
    )
    _, _, b_minus_dac = _terms(data, 0, n)
    plus = (1.0 - b_minus_dac / spec.v_fs) / 2.0
    if not np.all((plus == 0.0) | (plus == 1.0)):
        raise AssertionError("extracted ON mask is not binary; _terms changed its encoding")
    main_on = plus[:, :, : spec.dac_n_main].astype(np.int64)
    sub_on = plus[:, :, spec.dac_n_main :].astype(np.int64)
    return main_on, sub_on


def _pack_bits(bits: np.ndarray) -> int:
    """Pack a 0/1 vector into an integer, **LSB = physical address 0**.

    LSB-first on purpose: the RTL port is ``logic [N-1:0] main_on`` where index p
    is address p, so the testbench can compare the packed field with
    ``{1'b0, main_on[a]}`` directly. MSB-first packing would force the TB to
    reverse the field, which is exactly the kind of silent index error the
    contract's §6 A8 warns about.
    """
    value = 0
    for index, bit in enumerate(bits):
        if int(bit):
            value |= 1 << index
    return value


def build_m5(cfg: Config) -> tuple[str, dict[str, Any]]:
    """Direct bit-exact mask golden on a sid x (main_count, sub_count) grid.

    The grid is stated in **unit counts**, not codes: a code ``c`` maps to
    ``(main_count, sub_count) = (c // n_sub, c % n_sub)``, which is what the
    thermometer actually receives. Codes are rebuilt from the grid so that the
    golden still comes from the model's own ``_terms``.
    """
    n_active, n_sub = int(cfg.n_active), int(cfg.dac_n_sub)
    # 桥接零和交换**故意**让各 slice 的计数不同（那正是它的 DEM 作用），
    # 所以这个"均匀计数"网格必须把桥接关掉。桥接本身在 M3 的穷举里单独覆盖；
    # M5 对**非均匀** count 向量的行为由 TB 的稠密扫描（用 p1_m2_jinv.hex 当黄金）覆盖。
    uniform = replace(cfg, dem_bridge_enable=False)
    # 两个来源合起来：全部 512 个 sid 走边界计数（保证每个 sid 的映射都过一遍 M5），
    # 外加 8 个 sid 的中间计数（保证计数维度也稠密）。
    cases = [(s, 0, 0) for s in range(512)]
    cases += [(s, cfg.dac_n_main, 0) for s in range(512)]
    cases += [(s, mc, sc) for s in M5_SIDS for mc in M5_MAIN_COUNTS for sc in M5_SUB_COUNTS]
    sids = np.array([s for s, _, _ in cases], dtype=np.int64)
    codes = np.array([mc * n_sub + sc for _, mc, sc in cases], dtype=np.int64)
    main_on, sub_on = _m5_golden(uniform, sids, codes)

    lines = [
        "// p1_m5_masks.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: sid(3) main_count(2) sub_count(1) main_on[8](16 each) sub_on[8](2 each)",
        "// packed fields are LSB-first: bit p = physical main address p, bit q = sub address q.",
        "// dense sweep (512 sid x main_count 0..70) is recomputed in the TB from p1_m2_jinv.hex.",
        "#DATA",
    ]
    for i, (s, mc, sc) in enumerate(cases):
        main_fields = " ".join(_hex(_pack_bits(main_on[i, a]), 16) for a in range(n_active))
        sub_fields = " ".join(_hex(_pack_bits(sub_on[i, a]), 2) for a in range(n_active))
        lines.append(f"{_hex(s, 3)} {_hex(mc, 2)} {_hex(sc, 1)} {main_fields} {sub_fields}")

    # Structural self-check on the golden itself: the mask must be a pure thermometer.
    for i, (s, mc, sc) in enumerate(cases):
        for a in range(n_active):
            if int(main_on[i, a].sum()) != mc:
                raise AssertionError(
                    f"golden main mask for sid={s} main_count={mc} is not a thermometer"
                )
            if int(sub_on[i, a].sum()) != sc:
                raise AssertionError(
                    f"golden sub mask for sid={s} sub_count={sc} is not a thermometer"
                )
    stats = {
        "cases": len(cases),
        "all_sids_boundary_cases": 1024,
        "sids": list(M5_SIDS),
        "main_counts": list(M5_MAIN_COUNTS),
        "sub_counts": list(M5_SUB_COUNTS),
        "uniform_counts_require_bridge_off": True,
        "thermometer_structure_verified": True,
    }
    return "\n".join(lines) + "\n", stats


# ----------------------------------------------------------------------
# 链路向量：M1 -> M2 -> M3 -> M5 真实连通
# ----------------------------------------------------------------------
def build_chain(cfg: Config, n_samples: int = 256) -> tuple[str, dict[str, Any]]:
    """Stimulus + expected masks for the **connected** M1→M2→M3→M5 chain.

    Why this file exists: T1/T4/T5 各自把 DUT 的输入直接喂进去，`m2_sid` 是 TB 写死的
    常量。于是"M1 的 sid 有没有正确接到 M2"这件事**从未被验证过** —— 独立复核
    （2026-09-18）指出这是 P1 与后续阶段的接缝。本文件让 TB 只提供
    (bank, coarse, dither, bridge)，其余全部由 RTL 自己串起来：
    M1 出 sid -> M2 出逻辑位置 -> M3（sid_low 取自 M1）出计数 -> M5 出掩码。

    期望掩码由模型自己的 `_terms` 给出（见 `_m5_golden` 的提取说明）。

    Note:
        用 `dither_mode="quantizer"`：该模式下 dither 非零（让 M3 的 dither 支路也进链路），
        而 `_terms` 的采样 dither 分支**不会**被触发，故掩码提取仍然精确。
        `dem_enable=True` 是硬要求 —— 见 §0.2 的陷阱说明。

    Args:
        cfg: 已解析的配置；内部会施加本测试所需的覆盖项。
        n_samples: 采样数。

    Returns:
        ``(text, stats)``。
    """
    from adi_model.pipeline import run_pipeline
    from adi_model.sampler import sine_input

    run_cfg = replace(cfg, dem_enable=True, dither_mode="quantizer", dither_discrete=True)
    result = run_pipeline(
        run_cfg,
        sine_input(GOLDEN_AMPLITUDE_FRAC * cfg.v_fs, cfg.fs * GOLDEN_TONE_NUM / GOLDEN_TONE_DEN),
        n_samples,
    )
    units = int(cfg.dac_levels) // (2 ** int(cfg.b1))
    coarse = np.asarray(result.coarse[:n_samples], dtype=np.int64)
    k = np.asarray(np.rint(result.k[:n_samples]), dtype=np.int64)
    dither = k - coarse * units
    bank = np.asarray(result.bank[:n_samples], dtype=np.int64)
    sid = np.asarray(result.sid[:n_samples], dtype=np.int64)
    bridge = int(bool(cfg.dem_bridge_enable))

    # 掩码金标必须按**模型给的 sid**算，而不是按 RTL 的 sid —— 这样链路一旦错位就会红。
    uniform = replace(run_cfg, dem_bridge_enable=bool(bridge))
    codes = coarse * units + dither
    main_on, sub_on = _m5_golden(uniform, sid, codes)

    lines = [
        "// p1_chain.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: bank(1) coarse(3) dither(2 signed) bridge(1) "
        "main_on[8](16 each) sub_on[8](2 each)",
        "// 本文件**只给激励与期望掩码**，不给 main_count/sub_count：",
        "// 计数必须由 RTL 的 M3 自己算出来，否则这条链路测的就不是连通性。",
        "// sid_low 同理取自 RTL 的 M1 输出，不从文件读。",
        "#DATA",
    ]
    n_act = int(cfg.n_active)
    for i in range(n_samples):
        fields = " ".join(_hex(_pack_bits(main_on[i, a]), 16) for a in range(n_act))
        subf = " ".join(_hex(_pack_bits(sub_on[i, a]), 2) for a in range(n_act))
        lines.append(
            f"{bank[i] & 1} {_hex(int(coarse[i]), 3)} {_shex(int(dither[i]), 2)} {bridge} "
            + fields
            + " "
            + subf
        )

    stats = {
        "samples": n_samples,
        "dither_mode": "quantizer",
        "bridge": bridge,
        "nonzero_dither_samples": int(np.count_nonzero(dither != 0)),
        "distinct_sids": int(np.unique(sid[:n_samples]).size),
        "covers_m3_sid_low": True,
        "note": "T7 只驱动 bank/coarse/dither/bridge；sid/sid_low/count 全部由 RTL 产生",
    }
    return "\n".join(lines) + "\n", stats


# ----------------------------------------------------------------------
# P2：L0（div_floor / adc2_dec）、L2（oracle / 饱和 / 真实掩码 / 斜坡）、L3（链路）
# ----------------------------------------------------------------------
# 本导出器自己的 P2 规模与波形选择（常数而非魔数，便于外部复算）。
# 与 tools/export_rtl_params.py 的同名常量是各自独立的**选择**，不要求相等。
P2_TONE_NUM = 1
P2_TONE_DEN = 4096
P2_AMPLITUDE_FRAC = 1.0
# L3 链路的 coarse 必须覆盖 [0, 511] **全域**，否则"coarse ≈ 0 附近"没有对照值，
# 窄化实验在那里看到的 clip_high 只能登记、不能下结论。实测：A = 1.0*v_fs、f = fs/4096、
# 相位 0.5、4096 点是**唯一**一组一次跑满 512 个 coarse 的便宜配置（相位 0 会缺 125，
# 相位 1.5 缺 432，2/4096 缺 98/326，1/8192 跑 8192 点才满）。
# 这里刻意把边界情形一起收进来（会有 clip 与 rdac_over 行），因为它们正是要对照的那一段。
P2_LINK_PHASE = 0.5
P2_MASKS_TONE_NUM = 137
P2_MASKS_TONE_DEN = 4096
P2_MASKS_AMPLITUDE_FRAC = 0.62
P2_MASKS_SAMPLES = 512
P2_LINK_SAMPLES = 4096
P2_ALLOC_SAMPLES = 64
P2_RAMP_CARRIES = 511
P2_RAMP_HALF_SPAN = 64
# 抽稀后的斜坡偏移，单位 = 1/16 最终 LSB；完整网格是 -64..+64。
# 9 个点（-16,-12,-8,-4,0,4,8,12,16）会让文件超出 pre-commit 的
# `check-added-large-files --maxkb=512`：掩码列本身就要 8x63 bit = 135 B/行。
# 取 4 个点仍覆盖每个进位的两侧（rel_step < 0 与 > 0 各 2 行）。
P2_RAMP_REL_STEPS = (-16, -4, 4, 16)
P2_SAT_SCALE_BITS = 8
P2_SAT_ADC2_BITS = 4
VECTOR_LIMIT_BYTES = 512 * 1024

_P2_MEMO: dict[str, Any] = {}


def clear_p2_memo() -> None:
    """Drop the P2 memo so a caller can force a full recomputation."""
    _P2_MEMO.clear()


def _memo(key: str, factory):
    """Memoise one P2 sub-build; the 2**20 oracle is too expensive to redo."""
    if key not in _P2_MEMO:
        _P2_MEMO[key] = factory()
    return _P2_MEMO[key]


def _p2_oracle_model() -> FixedPointReconstructor:
    """Rebuild the ``straight_backend`` oracle by re-instantiating the module params."""
    spec = CalibrationSpec(
        dac_n_main=1,
        dac_n_sub=2,
        n_active=1,
        dac_complete_range=True,
        dem_enable=False,
        dem_bridge_enable=False,
        n_slices=1,
        v_fs=3.0,
        adc2_n_bits=20,
        adc2_v_min=0.0,
        adc2_v_max=6.0,
        dither_mode="off",
        dither_split_bank="sub",
        dither_units_range=0,
        dither_discrete=True,
    )
    return FixedPointReconstructor.from_weights(spec, [[0.5, 0.25, 0.25]])


def _p2_observation(spec, adc2_code, *, slice_ids=None, rdac_code=None, injection=None):
    """Assemble the minimal legal observation a golden computation needs."""
    n = len(adc2_code)
    return DigitalObservation(
        spec,
        np.zeros((n, spec.n_active), np.int64)
        if slice_ids is None
        else np.asarray(slice_ids, np.int64),
        np.zeros(n) if rdac_code is None else np.asarray(rdac_code, float),
        np.zeros(n, np.int64),
        np.asarray(adc2_code, np.int64),
        np.zeros(n),
        np.zeros(n) if injection is None else np.asarray(injection, float),
        np.zeros(n, bool),
        True,
    )


def _p2_on_masks(cfg: Config, slice_ids, sids, codes):
    """Recover the model's own unary ON masks by decoding ``_terms``.

    ``_terms`` folds the ON mask into ``b_minus_dac``; with the injection set to
    zero that affine map is exactly invertible. The result is asserted binary,
    so a change of encoding raises instead of silently producing a wrong golden.
    """
    if cfg.dither_mode == "sampling":
        raise ValueError("mask extraction is invalid for dither_mode='sampling'")
    spec = CalibrationSpec.from_config(cfg)
    n = len(codes)
    data = DigitalObservation(
        spec,
        np.asarray(slice_ids, np.int64),
        np.asarray(codes, float),
        np.asarray(sids, np.int64),
        np.zeros(n, np.int64),
        np.zeros(n),
        np.zeros(n),
        np.zeros(n, bool),
        True,
    )
    _, _, b_minus_dac = _terms(data, 0, n)
    plus = (1.0 - b_minus_dac / spec.v_fs) / 2.0
    if not np.all((plus == 0.0) | (plus == 1.0)):
        raise AssertionError("extracted ON mask is not binary; _terms changed its encoding")
    return (
        plus[:, :, : spec.dac_n_main].astype(np.int64),
        plus[:, :, spec.dac_n_main :].astype(np.int64),
    )


def _p2_operand_peaks(model: FixedPointReconstructor, data: DigitalObservation):
    """Measure the six checked operands and cross-check the model's own peak ledger.

    The measurement repeats the operand list of ``FixedPointReconstructor.reconstruct``
    only to obtain **width statistics** (contract §14 D3), never an expected value.
    It is validated against ``CodeStream.peak_accumulator_bits``, which the model
    computes independently; a disagreement raises.
    """
    fmt = model.format
    vscale = 2**fmt.voltage_fraction_bits
    wscale = 2**fmt.weight_fraction_bits
    count = 2**fmt.output_bits
    keys = ("op1", "op2", "op3", "num", "shifted", "denom")
    peaks = dict.fromkeys(keys, 0)
    n = len(data.rdac_code)
    for start in range(0, n, 256):
        stop = min(start + 256, n)
        ids, signal, b_minus_dac = _terms(data, start, stop)
        injection = data.common_injection_v[start:stop]
        signs = np.rint((b_minus_dac - injection[:, None, None]) / model.spec.v_fs)
        weights = model.weights_q[ids]
        rails = np.sum(weights * signs.astype(np.int64), axis=(1, 2))
        gains = np.sum(weights * signal.astype(np.int64), axis=(1, 2))
        totals = np.sum(weights, axis=(1, 2))
        for j in range(stop - start):
            k = start + j
            fine = model.adc2_min_q + round_even_divide(
                (2 * int(data.adc2_code[k]) + 1) * (model.adc2_max_q - model.adc2_min_q),
                2 ** (model.spec.adc2_n_bits + 1),
            )
            inj_q = int(np.rint(injection[j] / model.spec.v_fs * vscale))
            gain = int(gains[j])
            op1 = (fine - model.offset_q) * wscale
            op2 = int(rails[j]) * vscale
            op3 = int(totals[j]) * inj_q
            num = op1 - op2 - op3
            operands = (op1, op2, op3, num, (num + gain * vscale) * count, 2 * gain * vscale)
            for key, value in zip(keys, operands, strict=True):
                bits = abs(value).bit_length()
                if bits > peaks[key]:
                    peaks[key] = bits
    return {key: int(value) for key, value in peaks.items()}, max(1, max(peaks.values()) + 1)


def _p2_require_marker(text: str, name: str) -> None:
    """Refuse to ship a vector whose ``#DATA`` marker or body is malformed."""
    lines = text.splitlines()
    markers = [i for i, line in enumerate(lines) if line == "#DATA"]
    if len(markers) != 1 or not lines[markers[0] + 1]:
        raise AssertionError(f"{name}: #DATA marker or body is malformed")
    if not all(line.startswith("//") for line in lines[: markers[0]]):
        raise AssertionError(f"{name}: comment header contains a non-comment line")


def _p2_check_size(name: str, text: str) -> int:
    """Enforce the pre-commit 512 KB per-file budget and return the byte count."""
    size = len(text.encode("utf-8"))
    if size >= VECTOR_LIMIT_BYTES:
        raise AssertionError(f"{name} is {size} B, over the {VECTOR_LIMIT_BYTES} B budget")
    return size


# ----------------------------------------------------------------------
# 覆盖账本：每个向量文件、每个输入列的 {min, max, distinct}
# ----------------------------------------------------------------------
def _rep(prefix: str, count: int, *, signed: bool = False) -> tuple[tuple[str, bool], ...]:
    """Return ``count`` columns named ``prefix[0]`` … ``prefix[count-1]``."""
    return tuple((f"{prefix}[{i}]", signed) for i in range(count))


# 列名 + 是否有符号，顺序 = 文件里 token 的顺序。
# 这张表同时是一份**列数台账**：`_p2_coverage_audit` 会逐行核对 token 数，
# 于是"列定义变了、台账忘了改"会当场变红，而不是悄悄少记一列。
P2_AUDIT_COLUMNS: dict[str, tuple[tuple[str, bool], ...]] = {
    "p2_oracle_spec.hex": (("w0", False), ("w1", False), ("w2", False)),
    "p2_oracle_cfg.hex": (
        ("adc2_min_q", True),
        ("adc2_max_q", True),
        ("offset_q", True),
        ("adc2_n_bits", False),
        ("out_count", False),
        ("expected_identity", False),
    ),
    "p2_scalar.hex": (
        ("adc2_code", False),
        ("adc2_n_bits", False),
        ("adc2_min_q", True),
        ("adc2_max_q", True),
        ("offset_q", True),
        ("exp_fine_q", True),
        ("exp_ovf", False),
    ),
    "p2_div.hex": (("a", True), ("d", False), ("exp_q", True)),
    "p2_sat.hex": (
        ("inj_q", True),
        ("adc2_code", False),
        ("w_scale", False),
        ("exp_word", False),
        ("exp_clip_low", False),
        ("exp_clip_high", False),
    ),
    "p2_alloc.hex": (
        ("n", False),
        *_rep("acq", 8),
        *_rep("conv", 8),
        ("bank", False),
        ("conv_valid", False),
    ),
    "p2_masks.hex": (
        *_rep("slice_id", 8),
        *_rep("main_on", 8),
        *_rep("sub_on", 8),
        ("adc2_code", False),
        ("inj_q", True),
        ("exp_word", False),
        ("exp_clip_low", False),
        ("exp_clip_high", False),
    ),
    "p2_ramp.hex": (
        *_rep("slice_id", 8),
        *_rep("main_on", 8),
        *_rep("sub_on", 8),
        ("adc2_code", False),
        ("inj_q", True),
        ("exp_word", False),
        ("exp_clip_low", False),
        ("exp_clip_high", False),
        ("rel_step", True),
    ),
    "p2_recon_coef.hex": (("offset_q", True), ("adc2_min_q", True), ("adc2_max_q", True)),
    "p2_link_stim.hex": (
        ("bank", False),
        ("coarse", False),
        ("dither", True),
        ("inj_q", True),
        ("adc2_code", False),
        ("rdac_over", False),
        ("adc2_over", False),
        ("ra_sat", False),
    ),
    "p2_link_expected.hex": (
        ("dout", False),
        ("clip_low", False),
        ("clip_high", False),
        ("analog_ovf", False),
    ),
    "p2_link_weights.hex": (("slice", False), ("unit", False), ("w_q", False)),
}


def _decode_hex_token(token: str, signed: bool) -> int:
    """Decode one hex token with the field's own width (``int(..., 16)`` alone can't sign)."""
    value = int(token, 16)
    if signed:
        bits = 4 * len(token)
        if value >= 1 << (bits - 1):
            value -= 1 << bits
    return value


def _p2_data_rows(text: str) -> list[list[str]]:
    """Return the token rows that follow the single ``#DATA`` marker."""
    lines = text.splitlines()
    markers = [i for i, line in enumerate(lines) if line == "#DATA"]
    if len(markers) != 1:
        raise AssertionError("expected exactly one #DATA marker")
    return [line.split() for line in lines[markers[0] + 1 :] if line]


def _p2_coverage_audit(files: dict[str, str]) -> dict[str, Any]:
    """Ledger of ``{min, max, distinct}`` per input column, per vector file.

    Why it exists: "某个量到底量到了哪些值" 原本要逐文件翻；更要紧的是"某一列意外
    退化成常量"（例如 dither 全 0、inj_q 全 0）这类事故，在这里一眼可见。
    """
    audit: dict[str, Any] = {}
    for name, spec in P2_AUDIT_COLUMNS.items():
        text = files.get(name)
        if text is None:
            raise AssertionError(f"coverage_audit 登记了 {name}，但产物里没有它")
        rows = _p2_data_rows(text)
        columns: dict[str, dict[str, int]] = {}
        columns_values: list[list[int]] = [[] for _ in spec]
        for row in rows:
            if len(row) != len(spec):
                raise AssertionError(
                    f"{name}: 一行的 token 数是 {len(row)}，列台账写的是 {len(spec)}"
                )
            for index, (_, signed) in enumerate(spec):
                columns_values[index].append(_decode_hex_token(row[index], signed))
        for (column, _), values in zip(spec, columns_values, strict=True):
            columns[column] = {
                "min": min(values),
                "max": max(values),
                "distinct": len(set(values)),
            }
        audit[name] = {"rows": len(rows), "columns": columns}
    # JSON 寄存器镜像不是表，但同样要能被一眼审计
    regs = json.loads(files["p2_regs.json"])
    flat = [int(w) for row in regs["weights_q"] for w in row]
    audit["p2_regs.json"] = {
        "rows": None,
        "note": "JSON 寄存器镜像（不是表）；weights_q 按 18x71 展平后统计",
        "columns": {
            "weights_q": {"min": min(flat), "max": max(flat), "distinct": len(set(flat))},
            "offset_q": {"min": regs["offset_q"], "max": regs["offset_q"], "distinct": 1},
            "adc2_min_q": {"min": regs["adc2_min_q"], "max": regs["adc2_min_q"], "distinct": 1},
            "adc2_max_q": {"min": regs["adc2_max_q"], "max": regs["adc2_max_q"], "distinct": 1},
        },
    }
    return audit


# ----------------------------------------------------------------------
# L2 oracle：2**20 全码恒等（矩阵不落文件，只落常量与位宽实测）
# ----------------------------------------------------------------------
def build_p2_oracle() -> tuple[dict[str, str], dict[str, Any]]:
    """Export the oracle's three Q30 weights and its configuration constants."""

    def _factory():
        model = _p2_oracle_model()
        count = 2**model.format.output_bits
        data = _p2_observation(model.spec, np.arange(count, dtype=np.int64))
        stream = model.reconstruct(data)
        if not np.array_equal(stream.code, np.arange(count)):
            raise AssertionError("oracle construction no longer yields dout == adc2_code")
        peaks, observed = _p2_operand_peaks(model, data)
        if observed != stream.peak_accumulator_bits:
            raise AssertionError("operand measurement disagrees with the model's peak ledger")
        return model, stream, peaks, observed

    model, stream, peaks, observed = _memo("oracle", _factory)
    weights = [int(v) for v in model.weights_q.reshape(-1)]
    if len(weights) != 3 or sum(weights) != 2**30 or min(weights) <= 0:
        raise AssertionError("oracle weights must be three positive Q30 values summing to 2**30")
    count = 2**model.format.output_bits
    spec_text = "\n".join(
        [
            "// p2_oracle_spec.hex  (generated by tools/export_rtl_vectors.py)",
            "// cols: w0(12) w1(12) w2(12)   -- oracle 的 3 个 Q30 单位权重",
            "// Q30 source: FixedPointReconstructor.from_weights(spec, [[0.5, 0.25, 0.25]]),",
            f"// sum(w) = {sum(weights)} = 2**30.  三行内容相同：第 0 行是规范行，",
            "// 因此无论 TB 按“一行三个字段”还是“三行各读一次”取值，得到的都是同一组权重。",
            "// mask 全 0 -> plus = 0 -> s = +1 全部单位 -> rails = total = 2**30，I = 0。",
            "#DATA",
        ]
    )
    row = f"{_hex(weights[0], 12)} {_hex(weights[1], 12)} {_hex(weights[2], 12)}"
    spec_text += "\n" + "\n".join([row] * 3) + "\n"
    cfg_text = (
        "\n".join(
            [
                "// p2_oracle_cfg.hex  (generated by tools/export_rtl_vectors.py)",
                "// cols: adc2_min_q(16) adc2_max_q(16) offset_q(16) adc2_n_bits(2)",
                "//       out_count(6) expected_identity(1)",
                "// adc2_max_q = 2**33 是**实测**出来的、唯一让 dout == adc2_code 的取值：",
                "// delta = 2**33 与 adc2_n_bits = 20 给出 F = (2c+1)*2**12，",
                "// 于是 word = floor(F*2**62 / (2**30*2**33)) = floor((2c+1)/2) = c。",
                "// docs/rtl/P2_INTERFACE.md §12 写的 2**25 会让 word 恒为 0（已实测，见报告）。",
                "#DATA",
                f"{_hex(model.adc2_min_q & (2**64 - 1), 16)} "
                f"{_hex(model.adc2_max_q, 16)} {_hex(model.offset_q, 16)} "
                f"{_hex(model.spec.adc2_n_bits, 2)} {_hex(count, 6)} 1",
            ]
        )
        + "\n"
    )
    for name, text in (("p2_oracle_spec.hex", spec_text), ("p2_oracle_cfg.hex", cfg_text)):
        _p2_require_marker(text, name)
        _p2_check_size(name, text)
    stats = {
        "oracle_words": int(count),
        "weights_q": weights,
        "weights_sum": int(sum(weights)),
        "adc2_min_q": int(model.adc2_min_q),
        "adc2_max_q": int(model.adc2_max_q),
        "adc2_n_bits": int(model.spec.adc2_n_bits),
        "out_count": int(count),
        "identity_verified": True,
        "operand_peaks": peaks,
        "model_peak_accumulator_bits": int(observed),
        "peak_accumulator_bits": int(stream.peak_accumulator_bits),
    }
    return {"p2_oracle_spec.hex": spec_text, "p2_oracle_cfg.hex": cfg_text}, stats


# ----------------------------------------------------------------------
# L0 adc2_dec：定向用例（含 ties-to-even 的 8 个样例）
# ----------------------------------------------------------------------
def _p2_scalar_cases() -> list[tuple[int, int, int, int, int]]:
    """Return ``(adc2_code, min_q, max_q, offset_q, n_bits)`` directed cases."""
    cases: list[tuple[int, int, int, int, int]] = []
    # (1) ties-to-even。除数必须是 2：用 P_ADC2_BITS = 1（k = 2）驱动，
    #     并取 delta = 2x，于是 round_even_divide(2x, 4) == round_even_divide(x, 2)。
    #     取 delta = 4x 会退化成整除（余数恒为 0），一个平局都测不到。
    for x in (-7, -5, -3, -1, 1, 3, 5, 7):
        cases.append((0, 1000, 1000 + 2 * x, 0, 1))
    # (2) k = 3 的平局（delta ≡ 4 mod 8），两个奇偶方向都要有。
    for mn, delta in ((0, 4), (0, 12), (-50, -12), (-50, 20)):
        cases.append((0, mn, mn + delta, 0, 2))
        cases.append((1, mn, mn + delta, 0, 2))
    # (3) 系统性小位宽扫描：k = 2..5 × 边界 delta × 两个极端码。
    for n_bits in (1, 2, 3, 4):
        span = 2 ** (n_bits + 1)
        for delta in (1, -1, 2, -2, 3, -3, span, -span, span - 1, -(span - 1)):
            for code in (0, 2**n_bits - 1):
                cases.append((code, 7, 7 + delta, 0, n_bits))
    # (4) 生产量级：真的 adc2_min_q / adc2_max_q（paper_literal 名义几何）。
    for code in (0, 1, 100, 2**19, 2**20 - 2, 2**20 - 1):
        cases.append((code, -53687091, 590558003, 0, 20))
    # (5) 寄存器极端值：|-2**63| 端与 |2**63-1| 端，以及两端互换（负 delta）。
    for n_bits in (1, 4, 20):
        for code in (0, 2**n_bits - 1):
            cases.append((code, -(2**63), 2**63 - 1, 0, n_bits))
            cases.append((code, 2**63 - 1, -(2**63), 0, n_bits))
    # (6) offset_q 非零：adc2_dec 不读它，列仍在，用于钉住"它确实不参与"。
    for offset in (12345, -1, 2**62):
        cases.append((0, -100, 100, offset, 8))
    # (7) 最小量程。
    cases += [(0, 5, 6, 0, 1), (0, 5, 6, 0, 20), (0, -1, 0, 0, 1)]
    # (8) **生产位宽 12 的直接覆盖**。生产配置的 12 bit 路径原本只经
    #     p2_masks/p2_ramp/p2_link 由 recon_core 间接走到；这里补上直接用例：
    #     (a) 冻结要求的 delta = 2**33、min_q = 0 六个码；
    #     (b) 真实的生产寄存器三元组（与 p2_recon_coef.hex 同一组值）。
    #     两者都仍由模型的 round_even_divide 出期望，没有第二份公式。
    for code in (0, 1, 2047, 2048, 4094, 4095):
        cases.append((code, 0, 2**33, 0, 12))
    for code in (0, 2047, 4095):
        cases.append((code, -53687091, 590558003, 0, 12))
    return cases


def build_p2_scalar() -> tuple[str, dict[str, Any]]:
    """Export the directed ``adc2_dec`` golden (ties-to-even included)."""
    cases = _p2_scalar_cases()
    lines = [
        "// p2_scalar.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: adc2_code(3) adc2_n_bits(2) adc2_min_q(16) adc2_max_q(16) offset_q(16) "
        "exp_fine_q(16) exp_ovf(1)",
        "// exp_fine_q = adc2_min_q + round_even_divide((2*c+1)*(max-min), 2**(n_bits+1))，",
        "// 直接取自 Python 模型 adi_model.fixed_point.round_even_divide。",
        "// ⚠️ 冻结表里没有 adc2_n_bits 列：本文件**逐行**换 n_bits（1..20），没有它整份",
        "//    向量无法判读（P_ADC2_BITS 是 elaboration 期参数，不是运行时端口）。故加此列，",
        "//    列序为“紧跟 adc2_code”，其余 6 列顺序不变；该偏离登记在 p2_report.json。",
        "// ⚠️ 前 8 行是 ties-to-even 样例：adc2_n_bits = 1（除数 2 无法用 0 位端口表达）",
        "//    且 delta = adc2_max_q - adc2_min_q = 2x 为**负**（min_q > max_q）。",
        "//    这**刻意违反**载入期不变量 adc2_min_q < adc2_max_q —— 因为这是在单元测试",
        "//    舍入函数本身，不是生产配置。TB 必须绕过 calib_regs 的合法性校验直接驱动。",
        "//    负 delta 的用例数见 p2_report.json 的 scalar_min_gt_max_cases。",
        "// exp_ovf = 1 表示 fine_q 装不进 64 bit 有符号寄存器。",
        "#DATA",
    ]
    min_gt_max = 0
    ties: dict[int, int] = {}
    groups: dict[int, list[int]] = {}
    for index, (code, mn, mx, offset, n_bits) in enumerate(cases):
        if mn > mx:
            min_gt_max += 1
        fine = mn + round_even_divide((2 * code + 1) * (mx - mn), 2 ** (n_bits + 1))
        ovf = int(not -(2**63) <= fine < 2**63)
        if n_bits == 1 and code == 0 and mn == 1000:
            ties[(mx - mn) // 2] = fine - 1000
        groups.setdefault(n_bits, []).append(index)
        lines.append(
            f"{_hex(code, 3)} {_hex(n_bits, 2)} {_shex(mn, 16)} {_shex(mx, 16)} "
            f"{_shex(offset, 16)} {_shex(fine, 16)} {ovf}"
        )
    expected_ties = {-7: -4, -5: -2, -3: -2, -1: 0, 1: 0, 3: 2, 5: 2, 7: 4}
    if ties != expected_ties:
        raise AssertionError(f"ties-to-even samples drifted: {ties} != {expected_ties}")
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_scalar.hex")
    _p2_check_size("p2_scalar.hex", text)
    stats = {
        "cases": len(cases),
        "ties_to_even_samples": 8,
        "ties_to_even_result": {str(k): v for k, v in sorted(ties.items())},
        "scalar_min_gt_max_cases": min_gt_max,
        "scalar_min_gt_max_tie_cases": 4,
        "scalar_min_gt_max_note": (
            "冻结要求只登记 4（ties 组里恰好 4 个负 delta）；本文件为覆盖有符号路径"
            "还额外放了负 delta 的系统性用例，故总数更大。"
        ),
        "exp_ovf_set": int(sum(1 for ln in lines[14:] if ln.endswith(" 1"))),
        "adc2_n_bits_used": sorted(groups),
        "extra_column": "adc2_n_bits(2) inserted after adc2_code (frozen table omitted it)",
    }
    return text, stats


# ----------------------------------------------------------------------
# L0 div_floor：定向用例（穷举改成 TB 侧的定义式自检）
# ----------------------------------------------------------------------
def _p2_div_cases() -> list[tuple[int, int]]:
    """Return ``(a, d)`` directed cases for the signed floor divider."""
    divisors = (1, 2, 3, 2**13, 2**30, 2**60 - 1)
    cases = [(a, d) for d in divisors for a in (0, 1, -1, 2, -2)]
    for d in divisors:
        cases += [(d - 1, d), (1 - d, d), (d + 1, d), (-(d + 1), d)]
    big = 2**62 - 1
    cases += [(big, d) for d in divisors]
    cases += [(-big, d) for d in divisors]
    cases += [
        (0, 1),
        (big, 1),
        (-big, 1),
        (big, 2**60 - 1),
        (-big, 2**60 - 1),
        (2**31, 2**31),
        (-(2**31), 2**31),
        (2**61 + 1, 3),
        (-(2**61 + 1), 3),
    ]
    return sorted(set(cases))


def build_p2_div() -> tuple[str, dict[str, Any]]:
    """Export the directed ``div_floor`` golden plus its structural bound checks."""
    cases = _p2_div_cases()
    lines = [
        "// p2_div.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: a(16 signed) d(16) exp_q(16 signed)",
        "// exp_q = a // d —— Python 的 floor 除法，也就是 fixed_point.py 里 `shifted // denom`",
        "// 用的同一个算子（不是第二份实现）。**定向**用例只有几十条：",
        "// 真正的判据在 TB 侧的定义式自检——对每个 (a, d) 断言 q*d <= a < (q+1)*d（d > 0），",
        "// 用 >=128 bit 宽位算，独立于本模型，也不依赖本文件的期望值。",
        "// 约束：|a| < 2**62（P_W_A = 63 有符号）、0 < d < 2**60（P_W_D = 60 无符号）。",
        "#DATA",
    ]
    for a, d in cases:
        if not (0 < d < 2**60) or not (-(2**62) <= a < 2**62):
            raise AssertionError(f"div case ({a}, {d}) is outside the declared port widths")
        q = a // d
        if not -(2**62) <= q < 2**62:
            raise AssertionError(f"quotient {q} does not fit P_W_A")
        lines.append(f"{_shex(a, 16)} {_hex(d, 16)} {_shex(q, 16)}")
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_div.hex")
    _p2_check_size("p2_div.hex", text)
    stats = {
        "cases": len(cases),
        "negative_a": int(sum(1 for a, _ in cases if a < 0)),
        "zero_a": int(sum(1 for a, _ in cases if a == 0)),
        "d_is_one": int(sum(1 for _, d in cases if d == 1)),
        "divisors": [int(d) for d in sorted({d for _, d in cases})],
        "independent_judgement": "TB compares q*d <= a < (q+1)*d in >=128-bit arithmetic",
    }
    return text, stats


# ----------------------------------------------------------------------
# L2 饱和：输出剪裁与模拟饱和分开
# ----------------------------------------------------------------------
def _p2_sat_model(scale_bits: int) -> FixedPointReconstructor:
    """Return the oracle-ish model used by the saturation vectors."""
    spec = CalibrationSpec(
        dac_n_main=1,
        dac_n_sub=2,
        n_active=1,
        dac_complete_range=True,
        dem_enable=False,
        dem_bridge_enable=False,
        n_slices=1,
        v_fs=3.0,
        adc2_n_bits=P2_SAT_ADC2_BITS,
        adc2_v_min=0.0,
        adc2_v_max=6.0,
        dither_mode="off",
        dither_split_bank="sub",
        dither_units_range=0,
        dither_discrete=True,
    )
    scale = float(2**scale_bits)
    return FixedPointReconstructor.from_weights(spec, [[0.5 * scale, 0.25 * scale, 0.25 * scale]])


def _p2_sat_probe(model, code: int, inj_q: int) -> tuple[int, int, int]:
    """Return ``(word, clip_low, clip_high)`` for a one-sample probe."""
    spec = model.spec
    data = _p2_observation(
        spec, np.array([code], np.int64), injection=np.array([inj_q * spec.v_fs / 2**32])
    )
    stream = model.reconstruct(data)
    return int(stream.code[0]), int(stream.clipped_low[0]), int(stream.clipped_high[0])


def _p2_sat_threshold(model, code: int, *, want_low: bool, hi_q: int = 2**34) -> int:
    """Bisect the smallest ``|inj_q|`` whose probe clips at the requested end."""
    lo_q = 0
    while lo_q < hi_q:
        mid = (lo_q + hi_q) // 2
        _, low, high = _p2_sat_probe(model, code, mid if want_low else -mid)
        if low if want_low else high:
            hi_q = mid
        else:
            lo_q = mid + 1
    if lo_q >= 2**34:
        raise AssertionError(f"no clipping threshold found for adc2_code={code}")
    return lo_q


def build_p2_sat() -> tuple[str, dict[str, Any]]:
    """Export the saturation golden: clipping flags are not the analog overflow flag."""
    lines = [
        "// p2_sat.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: inj_q(16) adc2_code(3) w_scale(1) exp_word(5) exp_clip_low(1) exp_clip_high(1)",
        "// 口径复现 tests/unit/test_fixed_point.py::",
        "//   test_output_saturation_is_separate_from_analog_saturation（4 bit oracle 后端）。",
        "// w_scale 是本导出器定义的 1 bit 增益选择：0 = 权重 [0.5,0.25,0.25]（ΣW = 2**30）；",
        f"// 1 = 同一组权重寄存器左移 {P2_SAT_SCALE_BITS} 位（ΣW = 2**{30 + P2_SAT_SCALE_BITS} < 2**60，",
        "// 仍合法；TB 侧等价于 w_q_eff = w_q << 8）。它把 gain/denom 挪到另一个量级，",
        "// 但电压寄存器与 inj_q 都不变，于是入/出仍全部受检、期望仍由模型给出。",
        "// 期望值一律来自 FixedPointReconstructor.reconstruct，没有第二份公式。",
        "// ⚠️ 本文件的列里**没有** acc_ovf：冻结的列表达不了“粘滞溢出 + 保持上一拍值”。",
        "//    TB 必须额外断言这些行 acc_ovf == 0（它们都是算术合法的），",
        "//    溢出路径按 docs/rtl/P2_INTERFACE.md §13 由 TB 自己构造越界激励。",
        "#DATA",
    ]
    rows: list[str] = []
    base_inj = np.zeros(16)
    base_inj[0], base_inj[-1] = 0.4, -0.4
    codes = np.arange(16, dtype=np.int64)
    for scale_bits in (0, P2_SAT_SCALE_BITS):
        model = _p2_sat_model(scale_bits)
        stream = model.reconstruct(_p2_observation(model.spec, codes, injection=base_inj))
        for i in range(16):
            rows.append(
                f"{_shex(int(np.rint(base_inj[i] / 3.0 * 2**32)), 16)} {_hex(int(codes[i]), 3)} "
                f"{scale_bits > 0:d} {_hex(int(stream.code[i]), 5)} "
                f"{int(stream.clipped_low[i])} {int(stream.clipped_high[i])}"
            )
    directed = 0
    reached = 0
    for scale_bits in (0, P2_SAT_SCALE_BITS):
        model = _p2_sat_model(scale_bits)
        for code in (0, 15):
            for want_low, sign in ((True, 1), (False, -1)):
                thr = _p2_sat_threshold(model, code, want_low=want_low)
                for inj_q in (sign * (thr - 1), sign * thr):
                    word, low, high = _p2_sat_probe(model, code, inj_q)
                    rows.append(
                        f"{_shex(inj_q, 16)} {_hex(code, 3)} {scale_bits > 0:d} "
                        f"{_hex(word, 5)} {low} {high}"
                    )
                    directed += 1
                    if inj_q == sign * thr:
                        reached += low if sign > 0 else high
    if len(rows) > 64:
        raise AssertionError(f"p2_sat.hex has {len(rows)} rows, over the frozen 64-row budget")
    if reached != directed // 2:
        raise AssertionError("a directed saturation case failed to reach its clip flag")
    text = "\n".join(lines + rows) + "\n"
    _p2_require_marker(text, "p2_sat.hex")
    _p2_check_size("p2_sat.hex", text)
    stats = {
        "cases": len(rows),
        "oracle_reproduction_cases": 32,
        "directed_boundary_cases": directed,
        "directed_clip_flags_reached": int(reached),
        "w_scale_definition": (
            f"0 = sum(W)=2**30, 1 = weights << {P2_SAT_SCALE_BITS} (sum(W)=2**{30 + P2_SAT_SCALE_BITS})"
        ),
        "acc_ovf_column_present": False,
    }
    return text, stats


# ----------------------------------------------------------------------
# L0 slice_alloc：pingpong 表
# ----------------------------------------------------------------------
def build_p2_alloc(cfg: Config) -> tuple[str, dict[str, Any]]:
    """Export the 64-cycle A/B ping-pong allocation table straight from the model."""
    from adi_model.pipeline import run_pipeline
    from adi_model.sampler import sine_input

    plan = build_slice_plan(
        cfg,
        P2_ALLOC_SAMPLES,
        np.random.default_rng(cfg.seed + 4201),
        "pingpong",
        spare_period=None,
    )
    result = run_pipeline(
        cfg,
        sine_input(P2_AMPLITUDE_FRAC * cfg.v_fs, cfg.fs * P2_TONE_NUM / P2_TONE_DEN),
        P2_ALLOC_SAMPLES,
    )
    if result.conv_slice_ids is None or result.acq_slice_ids is None:
        raise AssertionError("the pipeline must expose both slice allocations")
    np.testing.assert_array_equal(np.asarray(result.acq_slice_ids)[:P2_ALLOC_SAMPLES], plan.acq)
    np.testing.assert_array_equal(np.asarray(result.conv_slice_ids)[:P2_ALLOC_SAMPLES], plan.conv)
    lines = [
        "// p2_alloc.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: n(2) acq0..acq7(2 each) conv0..conv7(2 each) bank(1) conv_valid(1)",
        "// 来源：timing.build_slice_plan(strategy='pingpong', spare_period=None)，",
        "//       且与 run_pipeline 的 acq_slice_ids / conv_slice_ids 逐元素核对通过。",
        "// bank 列取自 run_pipeline 实测的 result.bank（见报告 bank_equals_index_mod_2）。",
        "// conv_valid = (n >= 1)：第 0 拍还没有可转换的所有权。",
        "#DATA",
    ]
    bank = np.asarray(result.bank)[:P2_ALLOC_SAMPLES]
    for n in range(P2_ALLOC_SAMPLES):
        fields = [_hex(int(v), 2) for v in plan.acq[n]]
        fields += [_hex(int(v), 2) for v in plan.conv[n]]
        lines.append(f"{_hex(n, 2)} {' '.join(fields)} {int(bank[n]) & 1} {int(plan.valid[n])}")
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_alloc.hex")
    _p2_check_size("p2_alloc.hex", text)
    inv4a = bool(np.array_equal(plan.conv[1:], plan.acq[:-1]))
    stats = {
        "cycles": P2_ALLOC_SAMPLES,
        "inv_4a_conv_equals_previous_acq": inv4a,
        "acq_has_no_duplicates": bool(
            all(np.unique(plan.acq[n]).size == cfg.n_active for n in range(P2_ALLOC_SAMPLES))
        ),
        "max_slice_index": int(max(plan.acq.max(), plan.conv.max())),
        "bank_equals_index_mod_2": bool(np.all(bank == np.arange(P2_ALLOC_SAMPLES) % 2)),
    }
    if not inv4a:
        raise AssertionError("INV-4a (conv[n] == acq[n-1]) does not hold in the model")
    return text, stats


# ----------------------------------------------------------------------
# L2 真实掩码 / L3 链路：共用的采样与掩码行格式化
# ----------------------------------------------------------------------
def _p2_mask_row(slice_ids, main_on, sub_on, adc2_code, inj_q, word, low, high, extra=""):
    """Format one ``recon_core`` stimulus/expectation row (packed LSB = address 0)."""
    n_act = len(slice_ids)
    fields = [_hex(int(v), 2) for v in slice_ids]
    fields += [_hex(_pack_bits(main_on[a]), 16) for a in range(n_act)]
    fields += [_hex(_pack_bits(sub_on[a]), 2) for a in range(n_act)]
    return (
        " ".join(fields)
        + f" {_hex(adc2_code, 3)} {_shex(inj_q, 16)} {_hex(word, 5)} {low} {high}{extra}"
    )


def _p2_run(
    cfg: Config,
    *,
    tone_num: int,
    tone_den: int,
    amplitude_frac: float,
    samples: int,
    phase: float = 0.0,
):
    """Run the model on a sine and return the result plus its frozen register image."""
    from adi_model.pipeline import run_pipeline
    from adi_model.sampler import sine_input

    run_cfg = replace(cfg, dem_enable=True, dither_mode="quantizer", dither_discrete=True)
    result = run_pipeline(
        run_cfg,
        sine_input(amplitude_frac * run_cfg.v_fs, run_cfg.fs * tone_num / tone_den, phase),
        samples,
    )
    data = DigitalObservation.from_result(result)
    model = FixedPointReconstructor.from_result(result)
    stream = model.reconstruct(data)
    return run_cfg, result, data, model, stream


def _p2_pack_run(run_cfg, result, data, model, stream, *, samples: int):
    """Extract the shared per-sample fields the mask vectors need."""
    codes = np.asarray(np.rint(np.asarray(result.k)[:samples]), dtype=np.int64)
    sids = np.asarray(result.sid[:samples], dtype=np.int64)
    slice_ids = np.asarray(result.conv_slice_ids[:samples], dtype=np.int64)
    adc2 = np.asarray(result.adc2_code[:samples], dtype=np.int64)
    inj_q = np.asarray(
        [
            int(np.rint(v / model.spec.v_fs * 2**32))
            for v in np.asarray(data.common_injection_v)[:samples]
        ],
        dtype=np.int64,
    )
    main_on, sub_on = _p2_on_masks(run_cfg, slice_ids, sids, codes)
    return {
        "codes": codes,
        "sids": sids,
        "slice_ids": slice_ids,
        "adc2_code": adc2,
        "inj_q": inj_q,
        "main_on": main_on,
        "sub_on": sub_on,
        "word": np.asarray(stream.code[:samples], dtype=np.int64),
        "clip_low": np.asarray(stream.clipped_low[:samples], dtype=np.int64),
        "clip_high": np.asarray(stream.clipped_high[:samples], dtype=np.int64),
        "analog_ovf": np.asarray(stream.analog_overflow[:samples], dtype=np.int64),
    }


def build_p2_masks(cfg: Config) -> tuple[str, dict[str, Any], FixedPointReconstructor]:
    """Export 512 real ``recon_core`` mask cases taken from one production run.

    The third return value is the very ``FixedPointReconstructor`` instance the
    rows came from; ``build_p2_recon_coef`` reuses it instead of re-deriving the
    register triple from a nominal Vfs conversion (which would round differently).
    """
    samples = P2_MASKS_SAMPLES
    run_cfg, result, data, model, stream = _p2_run(
        cfg,
        tone_num=P2_MASKS_TONE_NUM,
        tone_den=P2_MASKS_TONE_DEN,
        amplitude_frac=P2_MASKS_AMPLITUDE_FRAC,
        samples=samples,
    )
    packed = _p2_pack_run(run_cfg, result, data, model, stream, samples=samples)
    lines = [
        "// p2_masks.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: slice_id[8](2 each) main_on[8](16 each) sub_on[8](2 each) adc2_code(3)",
        "//       inj_q(16) exp_word(5) exp_clip_low(1) exp_clip_high(1)",
        "// 掩码不是造出来的：由模型自己的 _terms 解码（见导出器 _p2_on_masks），",
        "// 断言二值后按 LSB = 物理地址 0 打包。slice_id 来自 run_pipeline 实测的 conv_slice_ids。",
        "// 期望 word/clip 来自 FixedPointReconstructor.reconstruct 的同一次运行。",
        f"// 波形：sine，f = fs*{P2_MASKS_TONE_NUM}/{P2_MASKS_TONE_DEN}，"
        f"A = {P2_MASKS_AMPLITUDE_FRAC}*v_fs，dem_en=1，dither_mode=quantizer。",
        "#DATA",
    ]
    for i in range(samples):
        lines.append(
            _p2_mask_row(
                packed["slice_ids"][i],
                packed["main_on"][i],
                packed["sub_on"][i],
                int(packed["adc2_code"][i]),
                int(packed["inj_q"][i]),
                int(packed["word"][i]),
                int(packed["clip_low"][i]),
                int(packed["clip_high"][i]),
            )
        )
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_masks.hex")
    _p2_check_size("p2_masks.hex", text)
    stats = {
        "cases": samples,
        "distinct_sids": int(np.unique(packed["sids"]).size),
        "slice_id_max": int(packed["slice_ids"].max()),
        "slice_alloc_uses_only_0_to_15": bool(packed["slice_ids"].max() < 16),
        "nonzero_injection_cases": int(np.count_nonzero(packed["inj_q"])),
        "clip_low_cases": int(packed["clip_low"].sum()),
        "clip_high_cases": int(packed["clip_high"].sum()),
        "analog_ovf_cases": int(packed["analog_ovf"].sum()),
        "thermometer_verified": True,
        "wave": {
            "tone": f"{P2_MASKS_TONE_NUM}/{P2_MASKS_TONE_DEN}",
            "amplitude_frac": P2_MASKS_AMPLITUDE_FRAC,
        },
    }
    for i in range(samples):
        for a in range(int(cfg.n_active)):
            if int(packed["main_on"][i][a].sum()) + int(packed["sub_on"][i][a].sum()) == 0:
                raise AssertionError(f"row {i} slice {a} has an empty mask; coverage is degenerate")
    return text, stats, model


def _p2_ramp_run(cfg: Config):
    """Run the full 511 x 129 dense ramp of the model's own monotonicity test."""
    from adi_model.pipeline import run_pipeline

    ramp_cfg = Config.paper_literal(
        dither_mode="off",
        dem_enable=False,
        mismatch_enable=False,
        enable_sampling_noise=False,
        ra_enable_noise=False,
        sadc_mismatch_enable=False,
        sadc_rdac_gain_mismatch=0,
    )
    lsb = ramp_cfg.lsb_target
    centers = -ramp_cfg.v_fs + np.arange(1, 512) * (2 * ramp_cfg.v_fs / 512)
    values = (
        centers[:, None] + np.arange(-P2_RAMP_HALF_SPAN, P2_RAMP_HALF_SPAN + 1)[None, :] * lsb / 16
    ).ravel()

    def waveform(t):
        return np.interp(t * ramp_cfg.fs, np.arange(values.size), values)

    result = run_pipeline(ramp_cfg, waveform, len(values))
    data = DigitalObservation.from_result(result)
    model = FixedPointReconstructor.from_result(result)
    stream = model.reconstruct(data)
    return ramp_cfg, result, data, model, stream, values.size


def build_p2_ramp(cfg: Config) -> tuple[str, dict[str, Any], FixedPointReconstructor]:
    """Export the thinned 511-carry ramp with both sides of every carry.

    Like ``build_p2_masks``, the third return value is the model instance itself,
    so the coefficient file can prove all three production runs agree.
    """
    ramp_cfg, result, data, model, stream, total = _memo("ramp", lambda: _p2_ramp_run(cfg))
    span = 2 * P2_RAMP_HALF_SPAN + 1
    if total != P2_RAMP_CARRIES * span:
        raise AssertionError(f"full ramp has {total} points, expected {P2_RAMP_CARRIES}x{span}")
    indices = np.array(
        [
            carry * span + rel + P2_RAMP_HALF_SPAN
            for carry in range(P2_RAMP_CARRIES)
            for rel in P2_RAMP_REL_STEPS
        ],
        dtype=np.int64,
    )
    codes = np.asarray(np.rint(np.asarray(result.k)), dtype=np.int64)[indices]
    sids = np.asarray(result.sid, dtype=np.int64)[indices]
    slice_ids = np.asarray(result.conv_slice_ids, dtype=np.int64)[indices]
    adc2 = np.asarray(result.adc2_code, dtype=np.int64)[indices]
    inj_q = np.asarray(
        [
            int(np.rint(v / model.spec.v_fs * 2**32))
            for v in np.asarray(data.common_injection_v)[indices]
        ],
        dtype=np.int64,
    )
    main_on, sub_on = _p2_on_masks(ramp_cfg, slice_ids, sids, codes)
    words = np.asarray(stream.code, dtype=np.int64)[indices]
    low = np.asarray(stream.clipped_low, dtype=np.int64)[indices]
    high = np.asarray(stream.clipped_high, dtype=np.int64)[indices]
    lines = [
        "// p2_ramp.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: slice_id[8](2 each) main_on[8](16 each) sub_on[8](2 each) adc2_code(3)",
        "//       inj_q(16) exp_word(5) exp_clip_low(1) exp_clip_high(1) rel_step(2 signed)",
        "// 模型跑的是完整的 511 进位 x 129 点（1/16 最终 LSB 间距）；本文件是**抽稀**后的",
        f"// 511 进位 x {len(P2_RAMP_REL_STEPS)} 点，rel_step 单位 = 1/16 最终 LSB。",
        "// ⚠️ 抽稀到 4 点（而不是 9 点）是**被迫**的：掩码列每行 135 B，",
        "//    4599 行 = 943 KB > pre-commit 的 512 KB 上限。4 点仍然覆盖每个进位的两侧",
        "//    （rel_step < 0 与 > 0 各有 2 行），跨度 2 个码、3 个单调区间 -> 跳码必被检出。",
        "// 每行按 rel_step 升序排列，TB 可直接检查 word 非降且相邻增量 <= 1。",
        "#DATA",
    ]
    for row in range(len(indices)):
        rel = int(P2_RAMP_REL_STEPS[row % len(P2_RAMP_REL_STEPS)])
        lines.append(
            _p2_mask_row(
                slice_ids[row],
                main_on[row],
                sub_on[row],
                int(adc2[row]),
                int(inj_q[row]),
                int(words[row]),
                int(low[row]),
                int(high[row]),
                extra=f" {_shex(rel, 2)}",
            )
        )
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_ramp.hex")
    size = _p2_check_size("p2_ramp.hex", text)
    reshaped = words.reshape(P2_RAMP_CARRIES, len(P2_RAMP_REL_STEPS))
    increments = np.diff(reshaped, axis=1)
    if not np.all((increments >= 0) & (increments <= 1)):
        raise AssertionError("thinned ramp is not monotone with increments in {0, 1}")
    rel = np.array(P2_RAMP_REL_STEPS)
    if not (np.any(rel < 0) and np.any(rel > 0)):
        raise AssertionError("the thinned ramp must keep rows on both sides of the carry")
    peaks, observed = _p2_operand_peaks(model, data)
    if observed != stream.peak_accumulator_bits:
        raise AssertionError("ramp operand measurement disagrees with the model's peak ledger")
    stats = {
        "rows": int(indices.size),
        "carries": P2_RAMP_CARRIES,
        "points_per_carry": len(P2_RAMP_REL_STEPS),
        "full_grid_rows": int(total),
        "rel_steps": [int(v) for v in P2_RAMP_REL_STEPS],
        "bytes": size,
        "full_grid_bytes_estimate": int(total * size / indices.size),
        "monotone_increments_max": int(increments.max()),
        "min_word": int(words.min()),
        "max_word": int(words.max()),
        "distinct_words": int(np.unique(words).size),
        "operand_peaks": peaks,
        "model_peak_accumulator_bits": int(observed),
        "inj_all_zero": bool(np.all(inj_q == 0)),
        "wave": {"carries": P2_RAMP_CARRIES, "grid": "-64..+64 in 1/16 LSB", "dither": "off"},
    }
    return text, stats, model


def build_p2_link(cfg: Config) -> tuple[dict[str, str], dict[str, Any], FixedPointReconstructor]:
    """Export the L3 link stimulus, the expected code stream and the register image.

    The third return value is the model behind ``p2_link_weights.hex`` /
    ``p2_regs.json`` / ``p2_link_expected.hex``, reused by ``build_p2_recon_coef``.
    """
    samples = P2_LINK_SAMPLES
    run_cfg, result, data, model, stream = _p2_run(
        cfg,
        tone_num=P2_TONE_NUM,
        tone_den=P2_TONE_DEN,
        amplitude_frac=P2_AMPLITUDE_FRAC,
        samples=samples,
        phase=P2_LINK_PHASE,
    )
    units = int(cfg.dac_levels) // (2 ** int(cfg.b1))
    coarse = np.asarray(result.coarse[:samples], dtype=np.int64)
    k = np.asarray(np.rint(np.asarray(result.k)[:samples]), dtype=np.int64)
    dither = k - coarse * units
    bank = np.asarray(result.bank[:samples], dtype=np.int64)
    adc2 = np.asarray(result.adc2_code[:samples], dtype=np.int64)
    inj_q = np.asarray(
        [
            int(np.rint(v / model.spec.v_fs * 2**32))
            for v in np.asarray(data.common_injection_v)[:samples]
        ],
        dtype=np.int64,
    )
    # 三个模拟域标志：数字-only 的 TB 里没有模拟链，只能由向量驱动。
    # 口径来自 weight_calibration.py:113 的 data.overflow = rdac_over|adc2_over|ra_sat，
    # 所以它们与 p2_link_expected.hex 第 4 列（analog_ovf）是同一份口径 —— 下面直接断言。
    rdac_over = np.asarray(result.rdac_over[:samples], dtype=np.int64)
    adc2_over = np.asarray(result.adc2_over[:samples], dtype=np.int64)
    ra_sat = np.asarray(result.ra_sat[:samples], dtype=np.int64)
    analog_or = rdac_over | adc2_over | ra_sat
    if not np.array_equal(analog_or, np.asarray(stream.analog_overflow[:samples], dtype=np.int64)):
        raise AssertionError(
            "rdac_over|adc2_over|ra_sat 与 reconstruct 的 analog_overflow 不一致 —— "
            "三列与 p2_link_expected.hex 第 4 列会脱节，TB 无法做 bit-exact 比对"
        )
    # 归属分布：谁把 analog_ovf 拉起来的（TB 侧会用同一批数字核对）
    attribution = {
        "both_rdac_and_adc2": int(np.count_nonzero(rdac_over & adc2_over)),
        "only_rdac": int(np.count_nonzero(rdac_over & ~adc2_over.astype(bool))),
        "only_adc2": int(np.count_nonzero(~rdac_over.astype(bool) & adc2_over)),
        "only_ra_sat": int(np.count_nonzero(ra_sat & ~analog_or.astype(bool))),
        "neither_rdac_nor_adc2": int(
            np.count_nonzero(~rdac_over.astype(bool) & ~adc2_over.astype(bool))
        ),
        "ra_sat_without_rdac_or_adc2": int(
            np.count_nonzero(ra_sat & ~(rdac_over | adc2_over).astype(bool))
        ),
    }
    stim_lines = [
        "// p2_link_stim.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: bank(1) coarse(3) dither(2 signed) inj_q(16) adc2_code(3)",
        "//       rdac_over(1) adc2_over(1) ra_sat(1)",
        "// **最外层激励**：RTL 必须自己从 bank 推出 sid(M1) -> 逻辑位置(M2) -> 计数(M3)",
        "// -> 掩码(M5) -> slice_alloc(M7)，再从 coarse+dither 重建 RDAC 码 k = coarse*units + dither",
        f"// （units = dac_levels/2**b1 = {units}）。中间量（sid、掩码、计数、slice_id）一律不给，",
        "// 这正是 P1 T7 的口径（docs/rtl/P1_INTERFACE.md §8.6）。",
        "// 掩码与 slice_id 全部由 RTL 自己产生；权重见 p2_link_weights.hex，寄存器见 p2_regs.json。",
        "// 末尾三列是**模拟域标志的驱动值**：数字-only TB 没有模拟链，只能由向量给；取值 0/1，",
        "// 取 bit[0]。三者之或恒等于 p2_link_expected.hex 第 4 列的 analog_ovf（导出期断言），",
        "// 所以 TB 可以独立复核 recon_core 的 a2ovf / clip 口径是否与契约 §4.6 一致。",
        "// ⚠️ 本文件的 coarse 覆盖 **[0, 511] 全域**（实测 512/512 个取值），这是刻意的：",
        f"//    波形 A = {P2_AMPLITUDE_FRAC}*v_fs、f = fs*{P2_TONE_NUM}/{P2_TONE_DEN}、"
        f"相位 {P2_LINK_PHASE}、{samples} 点。",
        "//    原来的 0.8*v_fs / 73/2048 / 512 点只覆盖 [50, 462]，于是 coarse ≈ 0 附近",
        "//    （桥接守卫 amount = min(1, min(code, 511-code)) 与 signs 零和交换的边界）",
        "//    在向量里**没有对照值**，观察到 clip_high 也只能登记、不能下结论。",
        f"//    行数因此从冻结表的 512 变成 {samples}（偏离已登记在 p2_report.json）。",
        "//    幅值顶到 ±v_fs 会带来少量 clip / rdac_over 行 —— 那正是要被对照的边界段。",
        "#DATA",
    ]
    exp_lines = [
        "// p2_link_expected.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: dout(5) clip_low(1) clip_high(1) analog_ovf(1)",
        "// 期望值 = FixedPointReconstructor.reconstruct（= SimResult.to_codes()）的逐样本输出。",
        "// analog_ovf = rdac_over | adc2_over | ra_sat，与 clip_low/high 互不替代（契约 §4.6）。",
        "// 行与 p2_link_stim.hex **逐行对应**（同一波形、同一索引）；本文件覆盖 coarse 全域，",
        "// 因此包含少量 clip / analog_ovf 为 1 的边界行 —— 那些是刻意要对照的，不是噪声。",
        "#DATA",
    ]
    weights_lines = [
        "// p2_link_weights.hex  (generated by tools/export_rtl_vectors.py)",
        "// cols: slice(2) unit(2) w_q(12)   -- 18 x 71 = 1278 个 Q30 权重",
        "// ⚠️ 冻结表的列宽写的是 slice(1)/unit(1)，但 slice 要到 17、unit 要到 70，",
        "//    1 个 hex 位（0..15）装不下；这里按 2 位写，行数不变（1278）。",
        "// 与 p2_regs.json 的 weights_q 逐项相同。",
        "#DATA",
    ]
    weights = np.asarray(model.weights_q, dtype=np.int64)
    for s in range(weights.shape[0]):
        for u in range(weights.shape[1]):
            weights_lines.append(f"{_hex(s, 2)} {_hex(u, 2)} {_hex(int(weights[s, u]), 12)}")
    for i in range(samples):
        stim_lines.append(
            f"{int(bank[i]) & 1} {_hex(int(coarse[i]), 3)} {_shex(int(dither[i]), 2)} "
            f"{_shex(int(inj_q[i]), 16)} {_hex(int(adc2[i]), 3)} "
            f"{int(rdac_over[i])} {int(adc2_over[i])} {int(ra_sat[i])}"
        )
        exp_lines.append(
            f"{_hex(int(stream.code[i]), 5)} {int(stream.clipped_low[i])} "
            f"{int(stream.clipped_high[i])} {int(stream.analog_overflow[i])}"
        )
    files = {
        "p2_link_stim.hex": "\n".join(stim_lines) + "\n",
        "p2_link_expected.hex": "\n".join(exp_lines) + "\n",
        "p2_link_weights.hex": "\n".join(weights_lines) + "\n",
    }
    for name, text in files.items():
        _p2_require_marker(text, name)
        _p2_check_size(name, text)
    regs = dict(model.to_dict())
    regs["dem_en"] = True
    regs["bridge_en"] = bool(run_cfg.dem_bridge_enable)
    files["p2_regs.json"] = _json_text(regs)
    dout = np.asarray(stream.code[:samples], dtype=np.int64)
    # ---- coarse 覆盖域：必须在**导出期**就断言满域 ----------------------------------
    # 只统计"实测到了什么"是不够的：波形参数改一点点就会悄悄缩回去（相位 0 缺 125、
    # 相位 1.5 缺 432 都是实测的）。这里把"补上了"变成一个会变红的性质，而不是一句声明。
    coarse_domain = np.unique(coarse)
    domain_missing = sorted(set(range(int(cfg.dac_levels))) - set(coarse_domain.tolist()))
    if int(coarse.min()) != 0 or int(coarse.max()) != int(cfg.dac_levels) - 1 or domain_missing:
        raise AssertionError(
            f"L3 激励的 coarse 没有覆盖全域: min={int(coarse.min())} max={int(coarse.max())} "
            f"distinct={coarse_domain.size}/{int(cfg.dac_levels)} 缺 {domain_missing[:12]}"
        )
    dither_fits = int(max(abs(int(dither.min())), abs(int(dither.max()))))
    if dither_fits > 127:
        raise AssertionError(f"dither = {dither_fits} 装不进 2 个 hex 字符的有符号列")
    peaks, observed = _p2_operand_peaks(model, data)
    if observed != stream.peak_accumulator_bits:
        raise AssertionError("link operand measurement disagrees with the model's peak ledger")
    stats = {
        "samples": samples,
        "weights_rows": int(weights.shape[0] * weights.shape[1]),
        "register_schema_version": int(regs["schema_version"]),
        "bank_equals_index_mod_2": bool(np.all(bank == np.arange(samples) % 2)),
        "dout_equals_adc2_code": bool(np.array_equal(dout, adc2)),
        "max_abs_dout_minus_adc2_code": int(np.max(np.abs(dout - adc2))),
        "clip_low_cases": int(np.count_nonzero(stream.clipped_low[:samples])),
        "clip_high_cases": int(np.count_nonzero(stream.clipped_high[:samples])),
        "analog_ovf_cases": int(np.count_nonzero(stream.analog_overflow[:samples])),
        "distinct_adc2_codes": int(np.unique(adc2).size),
        "adc2_code_max": int(adc2.max()),
        "adc2_n_bits": int(model.spec.adc2_n_bits),
        "distinct_sids": int(np.unique(np.asarray(result.sid[:samples])).size),
        "nonzero_dither_samples": int(np.count_nonzero(dither)),
        "nonzero_injection_samples": int(np.count_nonzero(inj_q)),
        "dither_range": [int(dither.min()), int(dither.max())],
        "coarse_range": [int(coarse.min()), int(coarse.max())],
        # coarse 覆盖域的**实测**账本（门禁拿它当独立复算的对照）
        "coarse_min": int(coarse.min()),
        "coarse_max": int(coarse.max()),
        "coarse_distinct": int(coarse_domain.size),
        "coarse_domain_expected": int(cfg.dac_levels),
        "coarse_low_rows": int(np.count_nonzero(coarse <= 49)),
        "coarse_high_rows": int(np.count_nonzero(coarse >= 463)),
        "coarse_complete": True,
        # 三列模拟域标志的实测账本（TB 用同一批数字核对）
        "analog_flag_rows": int(np.count_nonzero(analog_or)),
        "rdac_over_rows": int(np.count_nonzero(rdac_over)),
        "adc2_over_rows": int(np.count_nonzero(adc2_over)),
        "ra_sat_rows": int(np.count_nonzero(ra_sat)),
        "analog_flag_columns": ["rdac_over", "adc2_over", "ra_sat"],
        "analog_flag_or_matches_expected": True,
        "analog_flag_attribution": attribution,
        "units": units,
        "wave": {
            "config": "Config.paper_literal(dem_enable=True, dither_mode='quantizer', dither_discrete=True)",
            "tone": f"{P2_TONE_NUM}/{P2_TONE_DEN}",
            "amplitude_frac": P2_AMPLITUDE_FRAC,
            "phase": P2_LINK_PHASE,
            "samples": samples,
        },
        "operand_peaks": peaks,
        "model_peak_accumulator_bits": int(stream.peak_accumulator_bits),
    }
    return files, stats, model


# ----------------------------------------------------------------------
# 生产三系数：给 TB 的 recon_core 用（1 行 3 列）
# ----------------------------------------------------------------------
def build_p2_recon_coef(
    models: dict[str, FixedPointReconstructor],
) -> tuple[str, dict[str, Any]]:
    """Export the production ``(offset_q, adc2_min_q, adc2_max_q)`` triple as one row.

    The values are read off the **same** ``FixedPointReconstructor`` instances that
    produced ``p2_masks.hex`` / ``p2_ramp.hex`` / ``p2_link_*.hex`` — never
    re-derived from a nominal Vfs/adc2_v_max conversion, which rounds differently.
    The three instances must agree; a disagreement raises instead of shipping one
    of them silently.

    Args:
        models: ``{vector file name: the model instance that produced it}``.

    Returns:
        ``(text, stats)``; ``stats`` is also mirrored into the report's coverage
        and into ``recon_coef_source``.
    """
    if not models:
        raise AssertionError("the coefficient file needs at least one production model")
    fmt = next(iter(models.values())).format
    triples = {
        name: (int(m.offset_q), int(m.adc2_min_q), int(m.adc2_max_q)) for name, m in models.items()
    }
    distinct = set(triples.values())
    if len(distinct) != 1:
        raise AssertionError(f"the production runs disagree on the register triple: {triples}")
    offset_q, adc2_min_q, adc2_max_q = distinct.pop()
    bits = fmt.voltage_bits
    for name, value in (
        ("offset_q", offset_q),
        ("adc2_min_q", adc2_min_q),
        ("adc2_max_q", adc2_max_q),
    ):
        if not -(2 ** (bits - 1)) <= value < 2 ** (bits - 1):
            raise AssertionError(f"{name} = {value} does not fit the signed {bits}-bit register")
    if adc2_min_q >= adc2_max_q:
        raise AssertionError("the production backend range is empty")
    lines = [
        "// p2_recon_coef.hex  (generated by tools/export_rtl_vectors.py)",
        f"// cols: offset_q(16) adc2_min_q(16) adc2_max_q(16)  -- 均为 Q{fmt.voltage_fraction_bits} 有符号",
        "// 取自**生产链路**同一个 FixedPointReconstructor 实例（与 p2_masks.hex / p2_ramp.hex /",
        "// p2_link_expected.hex 同一模型）：min/max = rint(adc2_v_min|max / v_fs * 2**32)。",
        "// ⚠️ 不要按 Vfs=3.0、adc2_v_max=6.0 自己换算 —— 那会在舍入上差一。",
        "// 导出期已实测三份产物的三元组逐项相等；本文件与 p2_regs.json 的同名字段必须一致。",
        "#DATA",
        f"{_shex(offset_q, 16)} {_shex(adc2_min_q, 16)} {_shex(adc2_max_q, 16)}",
    ]
    text = "\n".join(lines) + "\n"
    _p2_require_marker(text, "p2_recon_coef.hex")
    _p2_check_size("p2_recon_coef.hex", text)
    stats = {
        "offset_q": offset_q,
        "adc2_min_q": adc2_min_q,
        "adc2_max_q": adc2_max_q,
        "sources": sorted(triples),
        "triples_agree": True,
        "adc2_n_bits": int(next(iter(models.values())).spec.adc2_n_bits),
    }
    return text, stats


def build_p2(cfg: Config) -> tuple[dict[str, str], dict[str, Any]]:
    """Assemble every P2 vector file plus its coverage/measurement report.

    Every section is memoised: the 2**20 oracle costs seconds to redo, and the
    drift gate compares against files **on disk**, so a stale memo cannot mask a
    drift. ``clear_p2_memo()`` forces a full recomputation (used by the
    determinism gate in ``tests/unit/test_rtl_vectors.py``).
    """
    files: dict[str, str] = {}
    oracle_files, oracle_stats = _memo("oracle_section", lambda: build_p2_oracle())
    files.update(oracle_files)
    scalar_text, scalar_stats = _memo("scalar_section", build_p2_scalar)
    files["p2_scalar.hex"] = scalar_text
    div_text, div_stats = _memo("div_section", build_p2_div)
    files["p2_div.hex"] = div_text
    sat_text, sat_stats = _memo("sat_section", build_p2_sat)
    files["p2_sat.hex"] = sat_text
    alloc_text, alloc_stats = _memo("alloc_section", lambda: build_p2_alloc(cfg))
    files["p2_alloc.hex"] = alloc_text
    masks_text, masks_stats, masks_model = _memo("masks_section", lambda: build_p2_masks(cfg))
    files["p2_masks.hex"] = masks_text
    ramp_text, ramp_stats, ramp_model = _memo("ramp_section", lambda: build_p2_ramp(cfg))
    files["p2_ramp.hex"] = ramp_text
    link_files, link_stats, link_model = _memo("link_section", lambda: build_p2_link(cfg))
    files.update(link_files)
    # 三系数文件必须与上面三条生产链路同源，故显式把模型实例传进去（不重新推导）。
    coef_text, coef_stats = _memo(
        "recon_coef_section",
        lambda: build_p2_recon_coef(
            {
                "p2_masks.hex": masks_model,
                "p2_ramp.hex": ramp_model,
                "p2_link_expected.hex": link_model,
            }
        ),
    )
    files["p2_recon_coef.hex"] = coef_text

    # 覆盖账本：读自己的产物，逐文件逐输入列给出实测的 {min, max, distinct}。
    coverage_audit = _p2_coverage_audit(files)

    # 三组位宽实测（契约 §14 D3）已经在各自的 builder 里量完并交叉核对过。
    sizes = {name: len(text.encode("utf-8")) for name, text in files.items()}
    rows = {
        name: len([ln for ln in text.splitlines() if ln and not ln.startswith(("//", "#"))])
        for name, text in files.items()
    }
    report = {
        "schema_version": 1,
        "generator": "tools/export_rtl_vectors.py",
        "config": "paper_literal",
        "files": sizes,
        "file_rows": rows,
        "largest_file_bytes": max(sizes.values()),
        "vector_limit_bytes": VECTOR_LIMIT_BYTES,
        "bank_equals_index_mod_2": link_stats["bank_equals_index_mod_2"],
        "oracle_property": (
            "2**20 全码 oracle 不落文件：输入就是循环下标本身（adc2_code = c），"
            "期望是性质 dout == adc2_code。TB 自己循环 2**20 次并逐码断言；本导出器只给出 "
            "3 个 Q30 权重（p2_oracle_spec.hex）与 min/max/offset/n_bits/out_count"
            "（p2_oracle_cfg.hex）。性质已在本机用模型跑满 2**20 个码验证通过。"
        ),
        "peak_bits": {
            "oracle": oracle_stats["operand_peaks"],
            "oracle_model_peak_accumulator_bits": oracle_stats["model_peak_accumulator_bits"],
            "ramp": ramp_stats["operand_peaks"],
            "ramp_model_peak_accumulator_bits": ramp_stats["model_peak_accumulator_bits"],
            "link": link_stats["operand_peaks"],
            "link_model_peak_accumulator_bits": link_stats["model_peak_accumulator_bits"],
            "note": (
                "每个数字是最坏样本上 |operand|.bit_length()。导出器用一份**测量**代码"
                "重算这 6 个受检操作数（只为位宽统计，不为期望值），并与模型自己的"
                " CodeStream.peak_accumulator_bits 交叉核对：max(bit_length)+1 必须等于它。"
            ),
        },
        "coverage": {
            "p2_oracle_spec.hex": oracle_stats,
            "p2_scalar.hex": scalar_stats,
            "p2_div.hex": div_stats,
            "p2_sat.hex": sat_stats,
            "p2_alloc.hex": alloc_stats,
            "p2_masks.hex": masks_stats,
            "p2_ramp.hex": ramp_stats,
            "p2_recon_coef.hex": coef_stats,
            "p2_link_stim.hex": {
                "rows": link_stats["samples"],
                "note": "只给最外层激励（含 3 列模拟域标志）；中间量全部由 RTL 产生",
                "coarse_min": link_stats["coarse_min"],
                "coarse_max": link_stats["coarse_max"],
                "coarse_distinct": link_stats["coarse_distinct"],
                "coarse_domain_expected": link_stats["coarse_domain_expected"],
                "coarse_low_rows": link_stats["coarse_low_rows"],
                "coarse_high_rows": link_stats["coarse_high_rows"],
                "coarse_complete": link_stats["coarse_complete"],
                "analog_flag_rows": link_stats["analog_flag_rows"],
                "rdac_over_rows": link_stats["rdac_over_rows"],
                "adc2_over_rows": link_stats["adc2_over_rows"],
                "ra_sat_rows": link_stats["ra_sat_rows"],
                "analog_flag_columns": link_stats["analog_flag_columns"],
                "analog_flag_or_matches_expected": link_stats["analog_flag_or_matches_expected"],
                "analog_flag_attribution": link_stats["analog_flag_attribution"],
            },
            "p2_link_expected.hex": {
                "rows": link_stats["samples"],
                "note": "与 p2_link_stim.hex 逐行对应；期望值来自同一次模型的 reconstruct",
            },
            "p2_link_weights.hex": {"rows": link_stats["weights_rows"]},
        },
        # 覆盖账本：逐文件、逐输入列的 {min, max, distinct}（实测，读自己的产物）
        "coverage_audit": coverage_audit,
        "recon_coef_source": (
            "FixedPointReconstructor.from_result(result) —— 即 p2_masks.hex / p2_ramp.hex / "
            "p2_link_expected.hex 背后那几个生产模型实例本身（不是按名义 Vfs 重算的）。"
            f"三份产物的 (offset_q, adc2_min_q, adc2_max_q) 已实测逐项相等"
            f"（{coef_stats['offset_q']}, {coef_stats['adc2_min_q']}, {coef_stats['adc2_max_q']}），"
            "不相等会在导出期直接报错。该三元组同时出现在 p2_regs.json 的同名字段里。"
        ),
        "link_checks": {
            "dout_equals_adc2_code": link_stats["dout_equals_adc2_code"],
            "max_abs_dout_minus_adc2_code": link_stats["max_abs_dout_minus_adc2_code"],
            "clip_low_cases": link_stats["clip_low_cases"],
            "clip_high_cases": link_stats["clip_high_cases"],
            "analog_ovf_cases": link_stats["analog_ovf_cases"],
            "distinct_adc2_codes": link_stats["distinct_adc2_codes"],
            "adc2_code_max": link_stats["adc2_code_max"],
            "distinct_sids": link_stats["distinct_sids"],
            "nonzero_dither_samples": link_stats["nonzero_dither_samples"],
            "nonzero_injection_samples": link_stats["nonzero_injection_samples"],
            "coarse_range": link_stats["coarse_range"],
            "dither_range": link_stats["dither_range"],
            "note": (
                "to_codes().code 与 adc2_code 不是同一个量（前者是最终 20 bit 字，后者是"
                "12 bit 后端码）；本链接测的是“给定最外层激励，RTL 是否给出同一条码流”。"
            ),
        },
        "waves": {
            "link": link_stats["wave"],
            "masks": masks_stats["wave"],
            "ramp": ramp_stats["wave"],
            "oracle": {
                "note": "无模拟链：输入就是 adc2_code 的循环下标，掩码全 0，I = 0",
            },
        },
        "scalar_min_gt_max_cases": scalar_stats["scalar_min_gt_max_cases"],
        "scalar_min_gt_max_tie_cases": scalar_stats["scalar_min_gt_max_tie_cases"],
        "sat_adc2_n_bits": P2_SAT_ADC2_BITS,
        "masks_adc2_n_bits": int(link_stats["adc2_n_bits"]),
        "findings": [
            "adc2_max_q 必须是 2**33（= adc2_max_q - adc2_min_q = 2**33 与 n_bits = 20 匹配），"
            "docs/rtl/P2_INTERFACE.md §12 写的 2**25 已实测会让 dout 恒为 0；"
            "TB 请以 p2_oracle_cfg.hex 为准。",
            "adc2_dec 的 ovf 输出在合法寄存器下**结构上不可达**：min_q/max_q ∈ [-2**63, 2**63)"
            "且 |delta| < 2**64 时 |round_even(...)| <= |delta|，故 fine_q 必落在 [-2**63, 2**63)。"
            "p2_scalar.hex 的 exp_ovf 全为 0 是**真实的结论**，不是漏测。",
            "p2_ramp.hex 按冻结表（511x9 = 4599 行）会是 943 KB，超过 pre-commit 的 512 KB"
            "上限（掩码列 135 B/行）。处置：列不变，点数降到 4（-1, -1/4, +1/4, +1 LSB），"
            "511 个进位全覆盖。",
            "p2_link_weights.hex 的冻结列宽 slice(1)/unit(1) 装不下 17/70，已按 2 位写，"
            "行数仍为 18x71 = 1278。",
            "p2_scalar.hex 的冻结列里没有 adc2_n_bits，而该文件**逐行**换 n_bits（1..20），"
            "没有这一列整份向量无法判读（P_ADC2_BITS 是 elaboration 期参数）。"
            "处置：在 adc2_code 之后插入 adc2_n_bits(2)，其余 6 列顺序不变。",
            "p2_sat.hex 整份文件固定在 adc2_n_bits = 4（复现 4 bit oracle 后端），"
            "TB 需用 P_ADC2_BITS = 4 重例化 recon_core；"
            "p2_masks/p2_ramp 用生产 ADC2_BITS（见 p2_regs.json 的 spec.adc2_n_bits）。",
            "冻结要求 scalar_min_gt_max_cases = 4（ties 组里的 4 个负 delta）。"
            "本文件为了真的覆盖有符号路径，还放了成组的负 delta 用例，"
            "故 scalar_min_gt_max_cases 是**实测总数**；ties 组的那 4 个另记为 "
            "scalar_min_gt_max_tie_cases。",
            "ties-to-even 的构造必须取 delta = 2x（不是 4x）：delta = 4x 时 "
            "round_even_divide(4x, 4) 是整除，余数恒为 0，一个平局都测不到；"
            "delta = 2x 才让 round_even_divide(2x, 4) == round_even_divide(x, 2)。",
            "p2_sat.hex 的冻结列里没有 acc_ovf，表达不了“粘滞溢出 + 保持上一拍值”的反例；"
            "溢出路径必须由 TB 自己构造越界激励并按 §13 判据检查。",
            "adc2_dec 的 n = (2c+1)*delta 在 W_MUL = 85 bit 内可能回绕（min_q = -2**63、"
            "max_q = 2**63-1、n_bits = 20 时 (2**21-1)*(2**64-1) > 2**84）；"
            "该极端组合没有对应的模型期望值，TB 不要用它做 bit-exact 比对。",
            "p2_recon_coef.hex 是**后续补发**的需求，不在最初的冻结表里：1 行 3 列，"
            "offset_q / adc2_min_q / adc2_max_q，全部取自生产链路的同一个 "
            "FixedPointReconstructor 实例。已实测 masks / ramp / link 三份产物的三元组"
            "逐项相等（0, -53687091, 590558003），并在导出期断言，防止两份产物脱节。",
            "p2_scalar.hex 新增了 9 行 n_bits = 12 的用例（生产位宽原本只经 "
            "p2_masks/p2_ramp/p2_link 间接覆盖）：6 行按 delta = 2**33 / min_q = 0，"
            "3 行用真实生产三元组 (0, -53687091, 590558003)。列不变。",
            "p2_link_stim.hex / p2_link_expected.hex 的行数从冻结表的 512 变成 4096："
            "窄化实验实测到原波形（0.8*v_fs、73/2048、512 点）的 coarse 只覆盖 [50, 462]，"
            "coarse ≈ 0 附近**没有对照值**，那里恰是桥接守卫 amount = min(1, min(code, 511-code)) "
            "与 signs 零和交换的边界，观察到 clip_high 也只能登记。换成 A = 1.0*v_fs、"
            "f = fs*1/4096、相位 0.5、4096 点后 coarse 覆盖 512/512 个取值（实测，导出期断言）。"
            "代价是引入少量 clip / analog_ovf 行（它们就是要对照的那一段）；"
            "列定义不变，TB 的 T9 按 EOF 读行，无需改。",
            "p2_link_stim.hex 追加了第 6/7/8 列 rdac_over(1) / adc2_over(1) / ra_sat(1)："
            "L3 是数字-only 的，模拟链不在 TB 里，这三个模拟域标志只能由向量驱动。"
            "三列取自 result.rdac_over / adc2_over / ra_sat，导出期断言它们之或恒等于 "
            "p2_link_expected.hex 第 4 列的 analog_ovf（= weight_calibration.py:113 的 "
            "data.overflow 口径），因此 TB 能独立复核 recon_core 的 a2ovf 口径。"
            "行数与行序都没动（仍 4096 行）。",
        ],
    }
    return files, report


# ----------------------------------------------------------------------
# 主流程
# ----------------------------------------------------------------------
def build(cfg_name: str) -> dict[str, Any]:
    """Produce every P1/P2 vector file in memory.

    Args:
        cfg_name: Key of the config factories; only ``paper_literal`` is supported
            (see the module docstring's applicable domain).

    Returns:
        ``{"files": {name: text}, "report": p1_report, "p2_report": p2_report}``.
    """
    if cfg_name != "paper_literal":
        raise ValueError(
            "P1 vectors are frozen for paper_literal only (H_ROT*W_ROT == 64 is a "
            "precondition of the M2 closed form); re-verify before adding topologies"
        )
    cfg = Config.paper_literal()
    cfg.check_legal()
    # ⚠️ 必须显式打开 dem_enable：工厂默认是 False，而 split_switch_command 在
    # dem_enable=False 时把 states 强制为 0，全部置换退化为恒等 —— 那样生成的
    # 向量会"全绿"却什么都没覆盖（子代理 B 独立复核时发现的陷阱）。
    if cfg.dem_enable:
        raise AssertionError("expected the stock config to be DEM-off; re-check the trap note")
    dem_cfg = replace(cfg, dem_enable=True)

    m1_text, m1_stats = build_m1(dem_cfg)
    m2_text, m2_stats, _ = build_m2(dem_cfg)
    m3_text, m3_stats = build_m3(cfg)
    m5_text, m5_stats = build_m5(dem_cfg)  # bridge off inside; see build_m5
    chain_text, chain_stats = build_chain(cfg)

    files = {
        "p1_m1_sid.hex": m1_text,
        "p1_m2_jinv.hex": m2_text,
        "p1_m3.hex": m3_text,
        "p1_m5_masks.hex": m5_text,
        "p1_chain.hex": chain_text,
    }
    p2_files, p2_report = build_p2(cfg)
    files.update(p2_files)
    report = {
        "schema_version": 1,
        "generator": "tools/export_rtl_vectors.py",
        "config": cfg_name,
        "m1": m1_stats,
        "m2": m2_stats,
        "m3": m3_stats,
        "m5": m5_stats,
        "chain": chain_stats,
        "effective_overrides": {"dem_enable": True},
        "header_default_note": (
            "rtl_params.vh 的 DEM_ENABLE 是**复位默认值**，取自 Config.paper_literal() 的"
            " dem_enable = False；P1 向量则按 dem_enable = True 生成（DEM 关闭时全部置换退化为"
            " 恒等，覆盖不到任何东西）。两者含义不同、不是矛盾，但集成时**必须**让寄存器把"
            " dem_en 打开，否则 RTL 会安静地退化成固定顺序。"
        ),
        "note": "M4 has no golden vector: PCG64 is not reproducible in RTL (interface doc §0.1).",
    }
    return {"files": files, "report": report, "p2_report": p2_report}


def main(argv: list[str] | None = None) -> int:
    """Run the P1/P2 vector exporter.

    Args:
        argv: Command-line arguments; ``None`` means ``sys.argv[1:]``.

    Returns:
        Process exit code: 0 on success, 1 when ``--check`` reports drift.
    """
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--config", default="paper_literal")
    ap.add_argument("--out-vectors", default="sim/vectors")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    root = pathlib.Path(__file__).resolve().parents[1]
    built = build(args.config)
    out_dir = root / args.out_vectors

    drift: list[str] = []
    for name, text in built["files"].items():
        _write(out_dir / name, text, check=args.check, drift=drift)
    _write(
        out_dir / "p1_vectors_report.json",
        _json_text(built["report"]),
        check=args.check,
        drift=drift,
    )
    _write(
        out_dir / "p2_report.json",
        _json_text(built["p2_report"]),
        check=args.check,
        drift=drift,
    )

    if not args.quiet:
        print(f"[export_rtl_vectors] config={args.config}")
        for name, text in built["files"].items():
            state = (
                "DRIFT"
                if str(out_dir / name) in drift
                else ("checked" if args.check else "written")
            )
            print(
                f"  [{state}] {name}  ({len(text.splitlines())} lines, {len(text) / 1024:.0f} KiB)"
            )
        for key in ("m1", "m2", "m3", "m5"):
            print(f"  {key}: {json.dumps(built['report'][key], ensure_ascii=False)}")
        print(
            "  p2: rows="
            + json.dumps(built["p2_report"]["file_rows"], ensure_ascii=False)
            + f"  largest={built['p2_report']['largest_file_bytes']} B"
        )
        print(f"  p2 peak_bits: {json.dumps(built['p2_report']['peak_bits'], ensure_ascii=False)}")
    if drift:
        print(f"[export_rtl_vectors] DRIFT: {len(drift)} artifact(s) differ", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
